// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqeOgK6m4A-bE6u85Lsg3wcm4F2DHCEw8',
    appId: '1:306355961206:web:3ea84bcada04fba3d20e57',
    messagingSenderId: '306355961206',
    projectId: 'fasum-app-aedff',
    authDomain: 'fasum-app-aedff.firebaseapp.com',
    storageBucket: 'fasum-app-aedff.firebasestorage.app',
    measurementId: 'G-W0PC1E2GLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUbw1vzEYsukxPK2IGvpkwOOG7nfWA9W0',
    appId: '1:306355961206:android:5ba7fd37d50cfee2d20e57',
    messagingSenderId: '306355961206',
    projectId: 'fasum-app-aedff',
    storageBucket: 'fasum-app-aedff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8GTU_61kc0O8ZNLBBWSYIILWYlwPh5WA',
    appId: '1:306355961206:ios:2ed49a1cabbc32e1d20e57',
    messagingSenderId: '306355961206',
    projectId: 'fasum-app-aedff',
    storageBucket: 'fasum-app-aedff.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8GTU_61kc0O8ZNLBBWSYIILWYlwPh5WA',
    appId: '1:306355961206:ios:2ed49a1cabbc32e1d20e57',
    messagingSenderId: '306355961206',
    projectId: 'fasum-app-aedff',
    storageBucket: 'fasum-app-aedff.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqeOgK6m4A-bE6u85Lsg3wcm4F2DHCEw8',
    appId: '1:306355961206:web:0f5c9f472442d8abd20e57',
    messagingSenderId: '306355961206',
    projectId: 'fasum-app-aedff',
    authDomain: 'fasum-app-aedff.firebaseapp.com',
    storageBucket: 'fasum-app-aedff.firebasestorage.app',
    measurementId: 'G-RRK3F5XSPY',
  );

}